/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
// import  { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type GLTFResult = GLTF & {
  nodes: {
    Generic_Les_Paul_Mesh: THREE.Mesh;
    Generic_Les_Paul_Mesh_1: THREE.Mesh;
    Generic_Les_Paul_Mesh_2: THREE.Mesh;
    Generic_Les_Paul_Mesh_3: THREE.Mesh;
    Generic_Les_Paul_Mesh_4: THREE.Mesh;
    Generic_Les_Paul_Mesh_5: THREE.Mesh;
    Generic_Les_Paul_Mesh_6: THREE.Mesh;
    Generic_Les_Paul_Mesh_7: THREE.Mesh;
    Generic_Les_Paul_Mesh_8: THREE.Mesh;
  };
  materials: {
    Plastic: THREE.MeshStandardMaterial;
    ["Golden Metal"]: THREE.MeshStandardMaterial;
    ["Fretboard Wood"]: THREE.MeshStandardMaterial;
    Ivory: THREE.MeshStandardMaterial;
    Finish: THREE.MeshStandardMaterial;
    ["Silver Metal"]: THREE.MeshStandardMaterial;
    Knobs: THREE.MeshStandardMaterial;
    ["Pickup Wrap Fabric"]: THREE.MeshStandardMaterial;
  };
};

export function Guitar(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/guitar.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Generic_Les_Paul_Mesh.geometry}
        material={materials.Plastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Generic_Les_Paul_Mesh_1.geometry}
        material={materials["Golden Metal"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Generic_Les_Paul_Mesh_2.geometry}
        material={materials["Fretboard Wood"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Generic_Les_Paul_Mesh_3.geometry}
        material={materials.Ivory}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Generic_Les_Paul_Mesh_4.geometry}
        material={materials.Finish}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Generic_Les_Paul_Mesh_5.geometry}
        material={materials["Silver Metal"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Generic_Les_Paul_Mesh_6.geometry}
        material={materials.Plastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Generic_Les_Paul_Mesh_7.geometry}
        material={materials.Knobs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Generic_Les_Paul_Mesh_8.geometry}
        material={materials["Pickup Wrap Fabric"]}
      />
    </group>
  );
}

useGLTF.preload("/guitar.gltf");
